### ISSUE TITLE
Add Plausible scripts to connectivity site

### ISSUE THREAD

**Issue by p-shahi** [pathfindertools/libp2p#9]
## Why Important

Get metrics on the website

**Comment by p-shahi** [comment]
@Dannys03 @tbenbow  any idea how to add it to this repo?

**Comment by salmad3** [comment]
Need to add it to the <head> of the site

**Comment by p-shahi** [comment]
> Need to add it to the of the site

Missed a word?

I added it to `_app.tsx` here: https://github.com/pathfindertools/libp2p/commit/19232bb0df00d9ed38c213808fa9482cda71860c

And looking at the console it looks like it's hooked up the Plausible

<img width="876" alt="image" src="https://user-images.githubusercontent.com/50885601/198863564-4405a23b-9633-4c89-8b5c-8a3151b367b0.png">

How can I see it on here: https://plausible.io/libp2p-microgen.vercel.app like https://plausible.io/docs.libp2p.io to test its working?

**Comment by p-shahi** [comment]
Done in https://github.com/pathfindertools/libp2p/commit/3d00bf84d3db4fe46842f9bacd8713fa9334735a
